apiVersion: v1
kind: Namespace
metadata:
  name: screamtest
  labels:
    name: screamtest

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: screamserviceaccount
  namespace: screamtest

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: screamrolebinding
roleRef:
  kind: Role
  name: screamrole
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: screamserviceaccount
    namespace: screamtest

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: screamrole
  labels:
    application: scream
rules:
  - apiGroups: [ "" ]
    #
    # at the HTTP level, the name of the resource for accessing Secret
    # objects is "secrets"
    resources: [ "secrets", "configmaps" ]
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
  - apiGroups: [ "" ]
    #
    # at the HTTP level, the name of the resource for accessing Secret
    # objects is "secrets"
    resources: [ "pods" ]
    verbs: [ "get", "list", "watch", "patch", "create" ]
  - apiGroups: [ "apps" ]
    #
    # at the HTTP level, the name of the resource for accessing Secret
    # objects is "secrets"
    resources: [ "deployments", "services" ]
    verbs: [ "get", "list", "watch", "patch", "update", "create" ]
  - apiGroups: [ "" ]
    resources: [ "endpoints", "services" ]
    verbs: [ "get", "list", "create", "update", "patch" ]
  - apiGroups: [ "" ]
    resources: [ "services" ]
    verbs: [ "get", "list", "create", "update", "patch" ]
