apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    scream.service: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      scream.service: nginx
  template:
    metadata:
      labels:
        scream.service: nginx
    spec:
      containers:
        - image: nginxdemos/hello
          name: nginx
          imagePullPolicy: Never
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
