apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    scream.service: scream
  name: scream
spec:
  replicas: 1
  selector:
    matchLabels:
      scream.service: scream
  template:
    metadata:
      labels:
        scream.service: scream
    spec:
      serviceAccountName: screamserviceaccount
      containers:
        - image: scream
          name: scream
          imagePullPolicy: Never
          command: [ "java", "-jar", "scream-0.0.1-SNAPSHOT.jar" ]
          ports:
            - containerPort: 80
              protocol: TCP
