name: Kubernetes verification

permissions:
  contents: read
  checks: write

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: K8s lint and verify
    runs-on: ubuntu-latest
    steps:
      - name: Execute k8s-lint with valid kubeconform
        uses: ./
        with:
          manifests: kubernetes/*
      - name: Execute k8s-lint with valid dryrun
        uses: ./
        with:
          lintType: dryrun
          manifests: kubernetes/*
